# Databricks notebook source
# MAGIC %md
# MAGIC # Summarize data using Azure Databricks

# COMMAND ----------

# MAGIC %md
# MAGIC Select the scored data generated by the Azure Data Factory pipeline

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from scoredflights

# COMMAND ----------

# MAGIC %md
# MAGIC Run the previous cell. You should see a table displayed with the scored data. Scroll all the way to the side. There you will find the prediction column containing the flight delay prediction provided by your machine learning model.

# COMMAND ----------

# MAGIC %md
# MAGIC In the following cell, you will create a table that summarizes the flight delays data. Instead of containing one row per flight, this new summary table will contain one row per origin airport at a given hour, along with a count of the quantity of anticipated delays. We also join the **airport_code_location_lookup_clean** table you created at the beginning of the lab, so we can extract the airport coordinates. 

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT  OriginAirportCode, Month, DayofMonth, CRSDepHour, Sum(prediction) NumDelays,
# MAGIC     CONCAT(Latitude, ',', Longitude) OriginLatLong
# MAGIC     FROM scoredflights s
# MAGIC     INNER JOIN airport_code_location_lookup_clean a
# MAGIC     ON s.OriginAirportCode = a.Airport
# MAGIC     WHERE Month = 4
# MAGIC     GROUP BY OriginAirportCode, OriginLatLong, Month, DayofMonth, CRSDepHour
# MAGIC     Having Sum(prediction) > 1
# MAGIC     ORDER BY NumDelays DESC

# COMMAND ----------

# MAGIC %md
# MAGIC The final step is to save this summary calculation as a table, which we can later query using Power BI (in the next exercise).

# COMMAND ----------

summary = spark.sql("SELECT  OriginAirportCode, Month, DayofMonth, CRSDepHour, Sum(prediction) NumDelays,     CONCAT(Latitude, ',', Longitude) OriginLatLong FROM scoredflights s INNER JOIN airport_code_location_lookup_clean a ON s.OriginAirportCode = a.Airport WHERE Month = 4 GROUP BY OriginAirportCode, OriginLatLong, Month, DayofMonth, CRSDepHour  Having Sum(prediction) > 1 ORDER BY NumDelays DESC")

# COMMAND ----------

summary.write.mode("overwrite").saveAsTable("flight_delays_summary")

# COMMAND ----------

# MAGIC %md
# MAGIC Execute the following to verify the table has data

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from flight_delays_summary

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC ## Next steps
# MAGIC 
# MAGIC You are done executing notebooks in this lab. Please continue to the next exercise, **Exercise 7: Visualizing in Power BI Desktop** in the hands-on lab document.
